---
title: "Topicos Lab"
author: "Carlos Zambrana-Torrelio"
date: '2022-04-22'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(vroom)
library(here)
library(sf)
library(fasterize)
library(ggspatial)
library(viridis)
```

Let's map the distribution of Mammarenavirus hosts. First, let's make a table with species and number of viruses.

```{r virion}
virion = vroom(here("data/Virion.csv.gz"))

virion %>%
  filter(Host == 'homo sapiens') %>%
  select(Virus) %>%
  distinct() %>%
  pull(Virus) -> zoonoses

virion %>%
  filter(VirusGenus == "mammarenavirus",
          HostOrder == "rodentia",
          DetectionMethod == "Isolation/Observation") %>%
  filter(Virus %in% zoonoses) %>%
  select(Host, Virus) %>%
  distinct() %>%
  group_by(Host) %>%
  summarize(NVirus = n_distinct(Virus)) -> nvir
   
```

Now let's read spatial data obtained from the IUCN.

```{r spatial, echo=FALSE}
iucn = st_read(here("data/rodents_arena/rodents_arena.shp"), layer = "rodents_arena")
#
# Merges results from VIRION and spatial data
#iucn %>% mutate(binomial = tolower(binomial)) %>%
#  left_join(nvir, by = c('binomial' = 'Host')) %>%
#  filter(NVirus > 0) -> iucn2
# Writes a new shapefile with the species identified as hosts for zoonotic Arenas
#st_write(iucn2, here('data/rodents_arena.shp'))

```

Let's map the results. First, we need to convert the IUCN polygons to rasters. We are using the `elevation` at a spatial resolution of 10' (check `prep_files.R`). 

```{r}
r = raster::raster(here("data/wc10/alt.bil"))
# Count the number of overlapping hosts
map.num.m = fasterize(iucn, r, field = NULL, fun = 'count')
# Sum the number of viruses per host
map.sum.m <- fasterize(iucn, r, field = "NVirus", fun = 'sum')

world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
```


```{r count}
ggplot() +
  layer_spatial(map.num.m) +
  geom_sf(data = world, color = "black", fill = NA, size = 0.3) +
  scale_fill_viridis(option = 'turbo', na.value = NA) +
  guides(fill = guide_colourbar(barwidth = 1, barheight = 8)) +
  theme_bw() + 
  theme(#legend.position = c(0.1, 0.35),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        #legend.background = element_rect(fill="#def3f6"),
        legend.key = element_rect(fill="#def3f6"),
        legend.text=element_text(size = 17)) +
  coord_sf(xlim = st_bbox(map.num.m)[c(1, 3)],
           ylim = st_bbox(map.num.m)[c(2, 4)],
           expand = FALSE)
```

```{r sum}
ggplot() +
  layer_spatial(map.sum.m) +
  geom_sf(data = world, color = "black", fill = NA, size = 0.3) +
  scale_fill_viridis(option = 'turbo', na.value = NA) +
  guides(fill = guide_colourbar(barwidth = 1, barheight = 8)) +
  theme_bw() + 
  theme(#legend.position = c(0.1, 0.35),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        #legend.background = element_rect(fill="#def3f6"),
        legend.key = element_rect(fill="#def3f6"),
        legend.text=element_text(size = 17)) +
  coord_sf(xlim = st_bbox(map.sum.m)[c(1, 3)],
           ylim = st_bbox(map.sum.m)[c(2, 4)],
           expand = FALSE)
```

